name = "OneRule"
uuid = "90484964-6d6a-4979-af09-8657dbed84ff"
authors = ["Roland Schätzle <roland.schaetzle@adviion.de>"]
version = "0.5.1"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
CategoricalArrays = "0.10"
MLJModelInterface = "^1"
Tables = "1.7"
julia = "1.6"
