name = "OneRule"
uuid = "90484964-6d6a-4979-af09-8657dbed84ff"
authors = ["Roland Schätzle <roland.schaetzle@adviion.de>"]
version = "0.2.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"

[compat]
CategoricalArrays = "0.10"
DataFrames = "1.3.0, 1.3.2"
MLJModelInterface = "^1"
julia = "1.7"
